import type { Criterion, DecisionTree } from "@/lib/data"

export interface DemoCriteriaBundle {
  tree: DecisionTree
  inclusion: Criterion[]
  determinationIssue?: { requirement: string; detail: string }
}

function inc(
  id: string,
  label: string,
  description: string,
  state: Criterion["state"],
  evidence: string,
  extra?: Partial<Criterion>,
): Criterion {
  return { id, label, description, state, evidence, ...extra }
}

function exc(
  id: string,
  label: string,
  description: string,
  state: Criterion["state"],
  evidence: string,
  extra?: Partial<Criterion>,
): Criterion {
  return { id, label, description, state, evidence, ...extra }
}

/** ag-demo-001 — Lumbar spinal fusion, in review; conservative therapy gap */
export const lumbarFusionDemoCriteria: DemoCriteriaBundle = {
  determinationIssue: {
    requirement: "A.3 (Failure of Conservative Management)",
    detail:
      "has not been satisfied — submitted PT records document only six weeks of structured therapy; policy CMS-L33747 requires twelve weeks minimum.",
  },
  inclusion: [],
  tree: {
    inclusion: [
      inc(
        "A.1",
        "Diagnosis: lumbar spondylolisthesis",
        "Radiographically confirmed spondylolisthesis grade II or higher at the level requested for fusion.",
        "met",
        "MRI Jan 2024 confirms grade II spondylolisthesis at L4-L5.",
        {
          sourceRef: "MRI_Lumbar_Spine_0108.png",
          patientMapping:
            "Orthopedic consult documents mechanical low back pain with left L5 radiculopathy correlating to L4-L5.",
          children: [
            inc(
              "A.1.a",
              "Grade II or higher on imaging",
              "Slip grade II+ documented on standing radiographs or MRI.",
              "met",
              "Radiology report: Meyerding grade II at L4-L5.",
              { sourceRef: "MRI_Lumbar_Spine_0108.png" },
            ),
            inc(
              "A.1.b",
              "Symptom correlation to index level",
              "Radicular or neurogenic claudication symptoms map to the fused level.",
              "met",
              "Exam documents left L5 dermatomal pain and positive straight leg raise.",
              { sourceRef: "Ortho_Consult_0108.pdf" },
            ),
          ],
        },
      ),
      inc(
        "A.2",
        "Instability or progressive deformity",
        "Documented spinal instability, progressive slip, or recurrent herniation with instability.",
        "met",
        "Serial imaging notes 4 mm progression over 12 months.",
        { sourceRef: "MRI_Lumbar_Spine_0108.png" },
      ),
      inc(
        "A.3",
        "Failure of conservative management",
        "Minimum twelve weeks of structured conservative therapy including PT, pharmacologic management, and activity modification unless contraindicated.",
        "not-met",
        "Only six weeks of physical therapy documented in appeal file.",
        {
          sourceRef: "PT_Records_Jan2024.pdf",
          rationale:
            "Policy requires twelve weeks minimum; submitted PT log covers Sep 15–Oct 28 only (6 weeks).",
          children: [
            inc(
              "A.3.a",
              "Structured physical therapy ≥ 12 weeks",
              "Active participation in supervised lumbar stabilization program.",
              "not-met",
              "12 sessions over 6 weeks; no extension documented.",
              { sourceRef: "PT_Records_Jan2024.pdf" },
            ),
            inc(
              "A.3.b",
              "NSAID or analgesic trial",
              "Documented trial of anti-inflammatory or analgesic therapy.",
              "met",
              "Meloxicam 15 mg daily × 8 weeks with partial relief.",
              { sourceRef: "Clinical_Notes_PCP.pdf" },
            ),
            inc(
              "A.3.c",
              "Epidural steroid injection when appropriate",
              "Trial of ESI unless contraindicated.",
              "not-found",
              "No ESI procedure note in submitted records.",
              {
                patientMapping:
                  "Appeal letter references planned ESI; no completed injection documented.",
              },
            ),
          ],
        },
      ),
      inc(
        "A.4",
        "Advanced imaging within 12 months",
        "MRI or CT of lumbar spine within twelve months preceding surgery request.",
        "met",
        "MRI dated Jan 8, 2024.",
        { sourceRef: "MRI_Lumbar_Spine_0108.png" },
      ),
      inc(
        "A.5",
        "Functional disability documented",
        "Oswestry Disability Index (ODI) ≥ 40 or equivalent functional limitation scale.",
        "met",
        "ODI 46 at orthopedic visit Jan 8, 2024.",
        { sourceRef: "Ortho_Consult_0108.pdf" },
      ),
      inc(
        "A.6",
        "Tobacco cessation requirement",
        "For elective fusion, six-week tobacco-free period prior to surgery or enrollment in cessation program.",
        "not-found",
        "Smoking status documented; no cessation program or quit date provided.",
        {
          sourceRef: "Clinical_Notes_PCP.pdf",
          patientMapping: "Chart notes active smoker as of Dec 2023 visit.",
        },
      ),
      inc(
        "A.7",
        "BMI and metabolic optimization",
        "BMI ≤ 40 or documented weight-management counseling if elevated.",
        "met",
        "BMI 31.2; nutrition counseling note on file.",
        { sourceRef: "Clinical_Notes_PCP.pdf" },
      ),
      inc(
        "A.8",
        "No prior fusion at same level",
        "No previous arthrodesis at the requested vertebral level.",
        "met",
        "Surgical history negative for prior lumbar fusion.",
        { sourceRef: "Ortho_Consult_0108.pdf" },
      ),
      inc(
        "A.9",
        "Surgeon qualification",
        "Operating surgeon board-certified or eligible in orthopedic or neurosurgical spine surgery.",
        "met",
        "Dr. Sam Chen — ABOS-certified orthopedic surgeon.",
        { sourceRef: "Appeal_Submission.pdf" },
      ),
      inc(
        "A.10",
        "Plan prior authorization on file",
        "Initial PA denial or medical necessity dispute documented for appealed level of service.",
        "met",
        "Denial letter Dec 18, 2023 for CPT 22612.",
        { sourceRef: "Denial_Letter_Dec2023.pdf" },
      ),
    ],
    exclusion: [
      exc(
        "E.1",
        "Active systemic or local infection",
        "Known active infection at operative site or systemic bacteremia.",
        "not-met",
        "No fever, elevated WBC, or wound infection in submitted labs.",
        { sourceRef: "Lab_Results_Basic.pdf" },
      ),
      exc(
        "E.2",
        "Fusion for isolated axial low back pain",
        "Fusion not indicated when only axial pain without radiculopathy or instability.",
        "not-met",
        "Radicular leg pain and grade II slip documented.",
        { sourceRef: "Ortho_Consult_0108.pdf" },
      ),
      exc(
        "E.3",
        "Untreated osteoporosis or metabolic bone disease",
        "Uncorrected bone disease increasing pseudoarthrosis risk.",
        "not-met",
        "DEXA T-score -1.8; not osteoporotic per policy threshold.",
        { sourceRef: "DEXA_Report_2023.pdf" },
      ),
      exc(
        "E.4",
        "Primary facet-mediated pain without instability",
        "Facet arthropathy as sole pain generator without surgical instability target.",
        "not-met",
        "Imaging demonstrates listhesis and foraminal stenosis.",
        { sourceRef: "MRI_Lumbar_Spine_0108.png" },
      ),
      exc(
        "E.5",
        "Incomplete skeletal maturity",
        "Fusion generally contraindicated in skeletally immature patients.",
        "not-met",
        "Patient age 39; skeletal maturity assumed.",
      ),
      exc(
        "E.6",
        "Untreated severe psychiatric instability",
        "Uncontrolled psychosis or active suicidality precluding informed surgical consent.",
        "not-met",
        "PHQ-9 score 6; no contraindication documented.",
        { sourceRef: "Clinical_Notes_PCP.pdf" },
      ),
      exc(
        "E.7",
        "Primary spinal malignancy",
        "Active neoplasm of spine or metastatic disease at index level.",
        "not-met",
        "No oncologic history in chart.",
        { sourceRef: "Clinical_Notes_PCP.pdf" },
      ),
      exc(
        "E.8",
        "High-dose opioid without pain management plan",
        "Chronic opioid > 90 MME without structured taper or PM consult.",
        "not-met",
        "Tramadol 50 mg PRN only; no high-dose opioid therapy.",
        { sourceRef: "Medication_List.pdf" },
      ),
      exc(
        "E.9",
        "Iatrogenic instability from prior decompression alone",
        "Prior laminectomy without fusion creating instability requiring revision context.",
        "not-met",
        "No prior lumbar decompression documented.",
        { sourceRef: "Ortho_Consult_0108.pdf" },
      ),
      exc(
        "E.10",
        "Pregnancy or planned pregnancy within recovery window",
        "Elective fusion deferred during pregnancy unless emergent.",
        "not-met",
        "Not applicable; male patient.",
      ),
    ],
  },
}

/** ag-demo-002 — Dupixent, approved */
export const dupixentDemoCriteria: DemoCriteriaBundle = {
  inclusion: [],
  tree: {
    inclusion: [
      inc(
        "A.1",
        "Diagnosis: moderate-to-severe atopic dermatitis",
        "ICD-10 L20.x with chronic eczematous dermatitis unresponsive to topicals.",
        "met",
        "Dermatology assessment confirms atopic dermatitis.",
        { sourceRef: "Derm_Assessment_Jan10.pdf" },
      ),
      inc(
        "A.2",
        "Age ≥ 18 years (adult indication)",
        "Patient meets FDA and plan age criteria for dupilumab.",
        "met",
        "Patient age 39.",
        { sourceRef: "Appeal_Submission.pdf" },
      ),
      inc(
        "A.3",
        "EASI score ≥ 16",
        "Eczema Area and Severity Index meets biologic threshold.",
        "met",
        "EASI 22 documented Jan 10, 2024.",
        { sourceRef: "Derm_Assessment_Jan10.pdf" },
      ),
      inc(
        "A.4",
        "Body surface area involvement ≥ 10%",
        "BSA involvement consistent with moderate-to-severe disease.",
        "met",
        "BSA 18% on exam.",
        { sourceRef: "Derm_Assessment_Jan10.pdf" },
      ),
      inc(
        "A.5",
        "IGA score ≥ 3",
        "Investigator Global Assessment moderate or severe.",
        "met",
        "IGA 4 (severe) at baseline visit.",
        { sourceRef: "Derm_Assessment_Jan10.pdf" },
      ),
      inc(
        "A.6",
        "Pruritus NRS ≥ 4",
        "Weekly average worst itch numeric rating scale ≥ 4.",
        "met",
        "Pruritus NRS 7/10 documented.",
        { sourceRef: "Derm_Assessment_Jan10.pdf" },
      ),
      inc(
        "A.7",
        "Failure of high-potency topical corticosteroid",
        "Adequate trial of potent topical steroid ≥ 4 weeks.",
        "met",
        "Clobetasol 0.05% BID × 8 weeks without adequate control.",
        { sourceRef: "Topical_Therapy_History.pdf" },
      ),
      inc(
        "A.8",
        "Trial of non-steroidal topical (e.g., crisaborole)",
        "Documented trial when not contraindicated.",
        "met",
        "Crisaborole 2% ointment × 4 weeks with partial response only.",
        { sourceRef: "Topical_Therapy_History.pdf" },
      ),
      inc(
        "A.9",
        "No concurrent live vaccine requirement conflict",
        "Immunization status compatible with biologic initiation per plan.",
        "met",
        "Immunization record reviewed; no live vaccine within 4 weeks.",
        { sourceRef: "Immunization_Record.pdf" },
      ),
      inc(
        "A.10",
        "Prescriber specialty appropriate",
        "Dermatology or allergy/immunology specialist managing biologic therapy.",
        "met",
        "Dr. Sam Chen — board-certified dermatology.",
        { sourceRef: "Derm_Assessment_Jan10.pdf" },
      ),
    ],
    exclusion: [
      exc(
        "E.1",
        "Active uncontrolled parasitic infection",
        "Helminth infection untreated prior to IL-4/IL-13 blockade.",
        "not-met",
        "No parasitic infection documented; travel history unremarkable.",
        { sourceRef: "Clinical_History.pdf" },
      ),
      exc(
        "E.2",
        "Known hypersensitivity to dupilumab or excipients",
        "Prior anaphylaxis or severe reaction to dupilumab.",
        "not-met",
        "No prior dupilumab exposure.",
        { sourceRef: "Medication_Allergy_List.pdf" },
      ),
      exc(
        "E.3",
        "Mild atopic dermatitis only",
        "Disease severity below biologic threshold on objective scores.",
        "not-met",
        "EASI 22 and IGA 4 exceed mild disease thresholds.",
        { sourceRef: "Derm_Assessment_Jan10.pdf" },
      ),
      exc(
        "E.4",
        "Inadequate topical trial duration",
        "Potent topical trial less than four weeks without justification.",
        "not-met",
        "Eight-week clobetasol trial documented.",
        { sourceRef: "Topical_Therapy_History.pdf" },
      ),
      exc(
        "E.5",
        "Uncontrolled ocular surface disease contraindicating",
        "Active severe conjunctivitis or keratitis precluding therapy.",
        "not-met",
        "Ophthalmology clearance note Jan 2024 — no active keratitis.",
        { sourceRef: "Ophth_Clearance.pdf" },
      ),
      exc(
        "E.6",
        "Primary diagnosis other than atopic dermatitis",
        "Psoriasis, contact dermatitis, or cutaneous T-cell lymphoma as primary driver.",
        "not-met",
        "Clinical morphology and history consistent with AD.",
        { sourceRef: "Derm_Assessment_Jan10.pdf" },
      ),
      exc(
        "E.7",
        "Pregnancy or breastfeeding",
        "Dupilumab pregnancy category considerations per plan.",
        "not-met",
        "Not pregnant; negative pregnancy test documented.",
        { sourceRef: "Lab_Results_Basic.pdf" },
      ),
      exc(
        "E.8",
        "Active malignancy requiring systemic therapy",
        "Uncontrolled cancer treatment taking priority over biologic initiation.",
        "not-met",
        "No active malignancy in history.",
        { sourceRef: "Clinical_History.pdf" },
      ),
      exc(
        "E.9",
        "Concurrent systemic immunosuppressant without washout",
        "Cyclosporine, methotrexate, or JAK inhibitor without adequate washout.",
        "not-met",
        "No concurrent systemic immunosuppression.",
        { sourceRef: "Medication_List.pdf" },
      ),
      exc(
        "E.10",
        "Cosmetic indication only",
        "Request for mild cosmetic skin improvement without functional severity.",
        "not-met",
        "Documented sleep disturbance and QOL impairment from pruritus.",
        { sourceRef: "Derm_Assessment_Jan10.pdf" },
      ),
    ],
  },
}

/** ag-demo-003 — SCS trial, denied */
export const scsTrialDemoCriteria: DemoCriteriaBundle = {
  determinationIssue: {
    requirement: "A.4 (Failed Conservative Management for Neuropathic Pain)",
    detail:
      "has not been satisfied — pain management records confirm only four weeks of multidisciplinary conservative therapy; policy requires twelve weeks minimum.",
  },
  inclusion: [],
  tree: {
    inclusion: [
      inc(
        "A.1",
        "Diagnosis: chronic intractable neuropathic pain",
        "Persistent neuropathic pain ≥ 6 months refractory to conservative care.",
        "met",
        "Lumbar radiculopathy/post-laminectomy syndrome × 14 months.",
        { sourceRef: "Pain_Management_Referral.pdf" },
      ),
      inc(
        "A.2",
        "Pain severity and functional impact",
        "Average pain NRS ≥ 6 and documented ADL limitation.",
        "met",
        "Average pain 7/10; unable to stand > 20 minutes.",
        { sourceRef: "Pain_Management_Referral.pdf" },
      ),
      inc(
        "A.3",
        "Anatomic target appropriate for SCS",
        "Pain distribution amenable to spinal cord or DRG stimulation.",
        "met",
        "Unilateral leg pain L4-L5 distribution.",
        { sourceRef: "Pain_Management_Referral.pdf" },
      ),
      inc(
        "A.4",
        "Failed conservative management",
        "Minimum twelve weeks structured multimodal therapy including PT, pharmacotherapy, and interventional options as appropriate.",
        "not-met",
        "Only four weeks of structured conservative care documented.",
        {
          sourceRef: "Conservative_Care_Summary.pdf",
          rationale:
            "Policy requires 12 weeks; records show Jan 2–Jan 30 program only.",
          children: [
            inc(
              "A.4.a",
              "Physical therapy ≥ 12 weeks",
              "Supervised lumbar/core stabilization program.",
              "not-met",
              "4 weeks PT (8 sessions) documented.",
              { sourceRef: "PT_Summary.pdf" },
            ),
            inc(
              "A.4.b",
              "Pharmacologic neuropathic pain trial",
              "Gabapentinoid, SNRI, or tricyclic adequate trial.",
              "met",
              "Gabapentin titrated to 900 mg TID with partial benefit.",
              { sourceRef: "Medication_List.pdf" },
            ),
          ],
        },
      ),
      inc(
        "A.5",
        "Psychological evaluation cleared",
        "Pre-SCS psychosocial screening without untreated major contraindication.",
        "met",
        "Psych eval Dec 2023 — cleared for SCS trial.",
        { sourceRef: "Psych_Eval_Dec2023.pdf" },
      ),
      inc(
        "A.6",
        "No untreated opioid use disorder",
        "PDMP review and substance use assessment acceptable.",
        "met",
        "PDMP review shows no aberrant filling patterns.",
        { sourceRef: "PDMP_Report.pdf" },
      ),
      inc(
        "A.7",
        "MRI compatibility screening",
        "No absolute contraindication to implanted device imaging.",
        "met",
        "Cervical MRI conditional; lumbar non-fusion status confirmed.",
        { sourceRef: "MRI_Lumbar_2023.pdf" },
      ),
      inc(
        "A.8",
        "Trial stimulator candidacy",
        "Patient willing and able to participate in 3–7 day trial period.",
        "met",
        "Informed consent and trial scheduling note on file.",
        { sourceRef: "Pain_Management_Referral.pdf" },
      ),
      inc(
        "A.9",
        "Implanting physician credentialing",
        "Physician credentialed for SCS trials per plan network.",
        "met",
        "In-network pain medicine physician.",
        { sourceRef: "Appeal_Submission.pdf" },
      ),
      inc(
        "A.10",
        "Prior authorization denial on file",
        "Initial utilization denial documented for appealed service.",
        "met",
        "Denial letter Jan 3, 2024 for CPT 63650.",
        { sourceRef: "Denial_Letter_Jan2024.pdf" },
      ),
    ],
    exclusion: [
      exc(
        "E.1",
        "Active systemic infection",
        "Bacteremia or active implant-site infection risk.",
        "not-met",
        "No active infection documented.",
        { sourceRef: "Lab_Results_Basic.pdf" },
      ),
      exc(
        "E.2",
        "Untreated coagulopathy",
        "INR or platelet abnormality precluding lead placement.",
        "not-met",
        "CBC and coag panel within normal limits.",
        { sourceRef: "Lab_Results_Basic.pdf" },
      ),
      exc(
        "E.3",
        "Demand for opioid elimination as sole indication",
        "SCS requested solely to eliminate all opioids without pain diagnosis support.",
        "not-met",
        "Neuropathic pain diagnosis primary; opioid sparing secondary goal.",
        { sourceRef: "Pain_Management_Referral.pdf" },
      ),
      exc(
        "E.4",
        "Primary somatoform pain disorder untreated",
        "Somatoform disorder without psychiatric treatment plan.",
        "not-met",
        "Psych eval does not identify somatoform primary diagnosis.",
        { sourceRef: "Psych_Eval_Dec2023.pdf" },
      ),
      exc(
        "E.5",
        "Pregnancy",
        "Implant trial generally deferred during pregnancy.",
        "not-met",
        "Not applicable.",
      ),
      exc(
        "E.6",
        "Incomplete spinal canal for lead placement",
        "Severe stenosis precluding safe lead insertion.",
        "not-met",
        "MRI shows moderate stenosis; interventionalist cleared anatomy.",
        { sourceRef: "MRI_Lumbar_2023.pdf" },
      ),
      exc(
        "E.7",
        "Active litigation for pain claim without clinical support",
        "Legal claim as sole driver without objective pain findings.",
        "not-met",
        "Objective exam findings and imaging support neuropathic pain.",
        { sourceRef: "Pain_Management_Referral.pdf" },
      ),
      exc(
        "E.8",
        "Pacemaker dependency without cardiology clearance",
        "Unmanaged cardiac device interaction risk.",
        "not-met",
        "No pacemaker documented.",
        { sourceRef: "Clinical_History.pdf" },
      ),
      exc(
        "E.9",
        "Prior failed SCS trial same anatomical target",
        "Previous adequate trial without benefit at same level.",
        "not-met",
        "No prior SCS trial documented.",
        { sourceRef: "Clinical_History.pdf" },
      ),
      exc(
        "E.10",
        "Non-neuropathic pain pattern only",
        "Purely nociceptive mechanical back pain without neuropathic component.",
        "not-met",
        "Burning dysesthesia and allodynia documented.",
        { sourceRef: "Pain_Management_Referral.pdf" },
      ),
    ],
  },
}

/** ag-demo-004 — Knee MRI, missing info */
export const kneeMriDemoCriteria: DemoCriteriaBundle = {
  determinationIssue: {
    requirement: "A.3 (Prior Weight-Bearing Radiographs) and A.5 (Conservative Therapy Duration)",
    detail:
      "could not be evaluated — required weight-bearing knee X-ray and duration of conservative management are not included in the appeal submission.",
  },
  inclusion: [],
  tree: {
    inclusion: [
      inc(
        "A.1",
        "Knee pain with suspected internal derangement",
        "Persistent knee pain with mechanical symptoms suggesting meniscal or ligament pathology.",
        "met",
        "Right knee pain × 8 weeks with locking sensation.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      inc(
        "A.2",
        "Focal exam findings",
        "Effusion, joint line tenderness, or limited ROM supporting advanced imaging.",
        "met",
        "Medial joint line tenderness and effusion on exam.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      inc(
        "A.3",
        "Prior weight-bearing radiographs",
        "Standing AP and lateral knee X-ray within six months before MRI.",
        "not-found",
        "No knee radiograph included in appeal package.",
        {
          patientMapping:
            "Clinic note references 'prior imaging at outside facility' without images attached.",
        },
      ),
      inc(
        "A.4",
        "Red flag screening completed",
        "No unexplained weight loss, fever, or history suggesting malignancy/infection.",
        "met",
        "Review of systems negative for red flags.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      inc(
        "A.5",
        "Conservative management trial",
        "Minimum four weeks structured conservative therapy before advanced imaging.",
        "not-found",
        "Home exercise mentioned; duration and structure not quantified.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      inc(
        "A.6",
        "NSAID or analgesic trial",
        "Documented pharmacologic pain management attempt.",
        "met",
        "Ibuprofen 600 mg TID × 2 weeks documented.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      inc(
        "A.7",
        "Mechanical symptoms duration",
        "Symptoms present ≥ 4 weeks to exclude acute self-limited injury.",
        "met",
        "Symptoms began Nov 15, 2023 (8+ weeks).",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      inc(
        "A.8",
        "Prior ultrasound or X-ray inconclusive",
        "Non-advanced imaging insufficient to establish diagnosis when performed.",
        "not-found",
        "No prior imaging reports submitted.",
      ),
      inc(
        "A.9",
        "Ordering provider appropriate specialty",
        "Orthopedics, sports medicine, or PM&R managing musculoskeletal knee complaint.",
        "met",
        "Orthopedic clinic order for MRI.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      inc(
        "A.10",
        "Correct laterality and CPT mapping",
        "Right knee MRI CPT 73721 matches clinical presentation.",
        "met",
        "Order specifies right knee without contrast.",
        { sourceRef: "Appeal_Submission.pdf" },
      ),
    ],
    exclusion: [
      exc(
        "E.1",
        "Acute traumatic injury < 4 weeks with Ottawa-negative low suspicion",
        "Recent trauma with low clinical suspicion per Ottawa rules.",
        "not-met",
        "No acute high-energy trauma; subacute presentation.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      exc(
        "E.2",
        "Primary osteoarthritis requiring TKR evaluation only",
        "Advanced OA Kellgren-Lawrence IV as sole indication without mechanical symptoms.",
        "not-met",
        "Mechanical locking symptoms suggest internal derangement.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      exc(
        "E.3",
        "Incidental MRI for unrelated body part",
        "Knee MRI bundled or ordered without knee-specific indication.",
        "not-met",
        "Indication clearly documents right knee internal derangement.",
        { sourceRef: "Appeal_Submission.pdf" },
      ),
      exc(
        "E.4",
        "Repeat MRI within 90 days without clinical change",
        "Duplicate advanced imaging without new exam findings.",
        "not-met",
        "No prior knee MRI within 90 days on file.",
        { sourceRef: "Clinical_History.pdf" },
      ),
      exc(
        "E.5",
        "Screening MRI without symptoms",
        "Asymptomatic surveillance not supported.",
        "not-met",
        "Symptomatic patient with functional limitation.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      exc(
        "E.6",
        "Pediatric open physis contraindication",
        "Advanced imaging deferred in skeletally immature patients when inappropriate.",
        "not-met",
        "Adult patient age 39.",
      ),
      exc(
        "E.7",
        "Infection suspected without labs",
        "Hot swollen joint requiring aspiration before MRI.",
        "not-met",
        "No systemic signs of septic arthritis.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      exc(
        "E.8",
        "Workers compensation without mechanism documentation",
        "Occupational claim without injury mechanism when required.",
        "not-met",
        "Non-occupational gradual onset documented.",
        { sourceRef: "Ortho_Clinic_Note.pdf" },
      ),
      exc(
        "E.9",
        "MRI contraindication (unsafe implant)",
        "Non-MRI-conditional implant precluding study.",
        "not-met",
        "Safety screening form negative for contraindications.",
        { sourceRef: "MRI_Safety_Screen.pdf" },
      ),
      exc(
        "E.10",
        "Experimental research protocol only",
        "Imaging solely for non-covered research enrollment.",
        "not-met",
        "Standard diagnostic intent documented.",
        { sourceRef: "Appeal_Submission.pdf" },
      ),
    ],
  },
}

/** ag-demo-005 — Rituximab, partially approved */
export const rituximabDemoCriteria: DemoCriteriaBundle = {
  determinationIssue: {
    requirement: "A.9 (Maintenance Rituximab Beyond Cycle 4)",
    detail:
      "is not supported in the submitted appeal — induction dosing meets criteria, but maintenance dosing beyond four cycles lacks documented disease activity metrics and prior biologic failure justification.",
  },
  inclusion: [],
  tree: {
    inclusion: [
      inc(
        "A.1",
        "Diagnosis: rheumatoid arthritis (seropositive)",
        "Established RA meeting ACR/EULAR criteria with active synovitis.",
        "met",
        "RA diagnosed 2019; RF and anti-CCP positive.",
        { sourceRef: "Rheum_History.pdf" },
      ),
      inc(
        "A.2",
        "Moderate-to-high disease activity",
        "DAS28-CRP > 3.2 or equivalent activity score at appeal baseline.",
        "met",
        "DAS28-CRP 4.6 at Jan 2024 visit.",
        { sourceRef: "Rheum_Clinic_Note.pdf" },
      ),
      inc(
        "A.3",
        "Methotrexate trial at adequate dose",
        "MTX ≥ 15 mg weekly (or max tolerated) for ≥ 12 weeks unless contraindicated.",
        "met",
        "MTX 20 mg weekly × 18 months documented.",
        { sourceRef: "Medication_History.pdf" },
      ),
      inc(
        "A.4",
        "TNF inhibitor failure or intolerance",
        "Inadequate response or contraindication to ≥ 1 anti-TNF agent.",
        "met",
        "Adalimumab discontinued Dec 2023 for secondary loss of response.",
        { sourceRef: "Prior_Biologic_Summary.pdf" },
      ),
      inc(
        "A.5",
        "No active serious infection",
        "No untreated TB, hepatitis B reactivation risk unmitigated, or active sepsis.",
        "met",
        "Quantiferon negative; HBV panel non-reactive.",
        { sourceRef: "Lab_Screening.pdf" },
      ),
      inc(
        "A.6",
        "Induction rituximab dosing appropriate",
        "Two 1000 mg IV infusions separated by two weeks (or weight-based equivalent).",
        "met",
        "Ordered induction: 1000 mg × 2 per protocol.",
        { sourceRef: "Treatment_Plan.pdf" },
      ),
      inc(
        "A.7",
        "Pre-medication protocol documented",
        "Acetaminophen, antihistamine, and methylprednisolone premed per FDA label.",
        "met",
        "Premedication orders included in infusion plan.",
        { sourceRef: "Treatment_Plan.pdf" },
      ),
      inc(
        "A.8",
        "Rheumatology specialist management",
        "Board-certified rheumatologist directing biologic therapy.",
        "met",
        "Dr. Sam Chen — rheumatology managing infusion series.",
        { sourceRef: "Rheum_Clinic_Note.pdf" },
      ),
      inc(
        "A.9",
        "Maintenance rituximab beyond cycle 4",
        "Repeat dosing supported by disease activity and prior cycle response.",
        "not-met",
        "Request includes q6mo maintenance × 12 months without cycle 1–4 response data.",
        {
          sourceRef: "Treatment_Plan.pdf",
          rationale:
            "Appeal documents planned maintenance but omits CD19 monitoring or DAS28 response after initial induction.",
        },
      ),
      inc(
        "A.10",
        "Live vaccine avoidance documented",
        "No live vaccine administered within window per B-cell depletion guidance.",
        "met",
        "Immunization record reviewed; no live vaccines planned.",
        { sourceRef: "Immunization_Record.pdf" },
      ),
    ],
    exclusion: [
      exc(
        "E.1",
        "Active hepatitis B infection",
        "HBsAg positive without antiviral prophylaxis plan.",
        "not-met",
        "HBsAg negative; HBcAb negative.",
        { sourceRef: "Lab_Screening.pdf" },
      ),
      exc(
        "E.2",
        "Latent TB untreated",
        "Positive Quantiferon without isoniazid or equivalent prophylaxis.",
        "not-met",
        "Quantiferon Gold negative.",
        { sourceRef: "Lab_Screening.pdf" },
      ),
      exc(
        "E.3",
        "NYHA Class IV heart failure",
        "Advanced CHF contraindicating rituximab infusion.",
        "not-met",
        "Cardiology note — EF 55%, no Class IV symptoms.",
        { sourceRef: "Cardiology_Clearance.pdf" },
      ),
      exc(
        "E.4",
        "Severe hypogammaglobulinemia untreated",
        "IgG < 400 mg/dL with recurrent infections without IVIG plan.",
        "not-met",
        "IgG 980 mg/dL.",
        { sourceRef: "Lab_Screening.pdf" },
      ),
      exc(
        "E.5",
        "Pregnancy or breastfeeding",
        "Rituximab contraindicated in pregnancy per plan.",
        "not-met",
        "Negative pregnancy test documented.",
        { sourceRef: "Lab_Screening.pdf" },
      ),
      exc(
        "E.6",
        "Primary CNS lymphoma history",
        "Prior malignancy contraindicating B-cell depletion without oncology clearance.",
        "not-met",
        "No lymphoma history.",
        { sourceRef: "Clinical_History.pdf" },
      ),
      exc(
        "E.7",
        "Concurrent cyclophosphamide without oncology indication",
        "Cytotoxic combination outside labeled RA protocol.",
        "not-met",
        "No cyclophosphamide ordered.",
        { sourceRef: "Treatment_Plan.pdf" },
      ),
      exc(
        "E.8",
        "Non-RA indication (off-label without policy coverage)",
        "Request for ANCA vasculitis or MS without covered indication.",
        "not-met",
        "Seropositive RA clearly documented.",
        { sourceRef: "Rheum_History.pdf" },
      ),
      exc(
        "E.9",
        "Inadequate methotrexate trial",
        "MTX dose or duration below policy minimum before biologic step therapy.",
        "not-met",
        "MTX 20 mg weekly × 18 months exceeds minimum.",
        { sourceRef: "Medication_History.pdf" },
      ),
      exc(
        "E.10",
        "Active serious infection within 4 weeks",
        "Hospitalized infection precluding immunosuppressive biologic.",
        "not-met",
        "No recent hospitalization for infection.",
        { sourceRef: "Clinical_History.pdf" },
      ),
    ],
  },
}

/** ag-demo-006 — Mavacamten, in review; missing echo/LVOT */
export const mavacamtenDemoCriteria: DemoCriteriaBundle = {
  determinationIssue: {
    requirement: "A.4 (Resting LVOT Gradient) and A.5 (Echocardiogram within 6 months)",
    detail:
      "could not be evaluated — most recent echocardiogram report and resting LVOT gradient values required for obstructive HCM pharmacotherapy are not included in the appeal file.",
  },
  inclusion: [],
  tree: {
    inclusion: [
      inc(
        "A.1",
        "Diagnosis: hypertrophic cardiomyopathy (oHCM)",
        "Echo or MRI confirming HCM with ventricular hypertrophy unexplained by secondary causes.",
        "met",
        "Cardiology note confirms HCM diagnosis established 2022.",
        { sourceRef: "Cardiology_Notes.pdf" },
      ),
      inc(
        "A.2",
        "Symptomatic obstructive physiology",
        "NYHA Class II–III dyspnea or angina attributable to LVOT obstruction.",
        "met",
        "NYHA Class II–III exertional dyspnea documented.",
        { sourceRef: "Cardiology_Notes.pdf" },
      ),
      inc(
        "A.3",
        "Beta-blocker or CCB trial at adequate dose",
        "Max tolerated first-line negative inotrope/chronotrope trial.",
        "met",
        "Metoprolol succinate 200 mg daily with persistent symptoms.",
        { sourceRef: "Medication_History.pdf" },
      ),
      inc(
        "A.4",
        "Resting LVOT gradient ≥ 30 mmHg",
        "Resting gradient or provocable gradient meeting mavacamten policy threshold.",
        "not-found",
        "No resting gradient value in submitted echo report.",
        {
          patientMapping:
            "Cardiology note references 'significant obstruction' without numeric gradient.",
        },
      ),
      inc(
        "A.5",
        "Echocardiogram within 6 months",
        "Transthoracic echo within six months of therapy initiation request.",
        "not-found",
        "Last echo report referenced is Aug 2023 — not included in appeal.",
        { sourceRef: "Cardiology_Notes.pdf" },
      ),
      inc(
        "A.6",
        "LVEF ≥ 55%",
        "Preserved ejection fraction required for mavacamten initiation.",
        "not-found",
        "EF value not present in submitted documentation.",
        { sourceRef: "Cardiology_Notes.pdf" },
      ),
      inc(
        "A.7",
        "Age ≥ 18 years",
        "Adult symptomatic obstructive HCM indication.",
        "met",
        "Patient age 39.",
        { sourceRef: "Appeal_Submission.pdf" },
      ),
      inc(
        "A.8",
        "Cardiology specialist management",
        "HCM-experienced cardiologist directing therapy and monitoring plan.",
        "met",
        "Follows HCM center; Dr. Sam Chen cardiology.",
        { sourceRef: "Cardiology_Notes.pdf" },
      ),
      inc(
        "A.9",
        "Pregnancy prevention plan (REMS)",
        "Mavacamten REMS enrollment and contraception counseling documented.",
        "met",
        "REMS enrollment form and contraception attestation included.",
        { sourceRef: "REMS_Enrollment.pdf" },
      ),
      inc(
        "A.10",
        "Baseline troponin and BNP monitoring plan",
        "Plan for serial biomarker monitoring per label and policy.",
        "met",
        "Monitoring schedule documented in treatment plan.",
        { sourceRef: "Treatment_Plan.pdf" },
      ),
    ],
    exclusion: [
      exc(
        "E.1",
        "LVEF < 55%",
        "Reduced ejection fraction contraindicating mavacamten.",
        "not-found",
        "EF not documented in appeal — cannot exclude.",
        { sourceRef: "Cardiology_Notes.pdf" },
      ),
      exc(
        "E.2",
        "Advanced heart failure (NYHA IV)",
        "Decompensated heart failure requiring inotropic support.",
        "not-met",
        "Ambulatory NYHA II–III; no recent hospitalization for ADHF.",
        { sourceRef: "Cardiology_Notes.pdf" },
      ),
      exc(
        "E.3",
        "Permanent atrial fibrillation without rate control plan",
        "Uncontrolled AF increasing embolic and hemodynamic risk.",
        "not-met",
        "Normal sinus rhythm on last clinic ECG.",
        { sourceRef: "ECG_Report.pdf" },
      ),
      exc(
        "E.4",
        "Dual strong CYP2C19 inhibitors",
        "Contraindicated drug interaction per labeling.",
        "not-met",
        "Medication review negative for strong CYP2C19 inhibitors.",
        { sourceRef: "Medication_History.pdf" },
      ),
      exc(
        "E.5",
        "Pregnancy or breastfeeding",
        "Embryo-fetal toxicity risk — absolute contraindication.",
        "not-met",
        "Negative pregnancy test; REMS contraception plan active.",
        { sourceRef: "REMS_Enrollment.pdf" },
      ),
      exc(
        "E.6",
        "Non-obstructive HCM without gradient",
        "HNCM without measurable LVOT obstruction when symptomatic.",
        "not-found",
        "Obstructive physiology asserted but gradient values missing.",
        { sourceRef: "Cardiology_Notes.pdf" },
      ),
      exc(
        "E.7",
        "Recent septal reduction therapy within 3 months",
        "Surgical myectomy or alcohol septal ablation too recent for add-on.",
        "not-met",
        "No prior septal reduction procedure.",
        { sourceRef: "Clinical_History.pdf" },
      ),
      exc(
        "E.8",
        "Severe hypotension (SBP < 90)",
        "Symptomatic hypotension precluding negative inotrope therapy.",
        "not-met",
        "Clinic BP 118/72 mmHg.",
        { sourceRef: "Cardiology_Notes.pdf" },
      ),
      exc(
        "E.9",
        "Active liver disease (Child-Pugh B/C)",
        "Hepatic impairment contraindicating mavacamten metabolism.",
        "not-met",
        "LFTs within normal limits.",
        { sourceRef: "Lab_Results_Basic.pdf" },
      ),
      exc(
        "E.10",
        "Disopyramide contraindication not addressed",
        "Disopyramide trial omitted without documented intolerance when required by plan.",
        "not-met",
        "Disopyramide trial documented — stopped for anticholinergic side effects.",
        { sourceRef: "Medication_History.pdf" },
      ),
    ],
  },
}

export const demoCriteriaByAppealId: Record<string, DemoCriteriaBundle> = {
  "ag-demo-001": lumbarFusionDemoCriteria,
  "ag-demo-002": dupixentDemoCriteria,
  "ag-demo-003": scsTrialDemoCriteria,
  "ag-demo-004": kneeMriDemoCriteria,
  "ag-demo-005": rituximabDemoCriteria,
  "ag-demo-006": mavacamtenDemoCriteria,
}

// Populate flat inclusion arrays from trees
for (const bundle of Object.values(demoCriteriaByAppealId)) {
  bundle.inclusion = bundle.tree.inclusion
}
